from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo
from typing import Any

from sqlalchemy import MetaData, Table, create_engine, func, inspect, or_, select, text, update
from sqlalchemy.engine import Engine

from app.admin.settings import DEFAULT_ADMIN_SETTINGS
from app.database.bootstrap import bootstrap_database, database_inventory
from app.services.decision_snapshot_service import DecisionSnapshotService


SCHEMA = [
"""CREATE TABLE IF NOT EXISTS predictions (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fixture_id BIGINT NOT NULL, created_at TEXT NOT NULL, league TEXT, home_team TEXT, away_team TEXT,
 pick TEXT, pick_role TEXT DEFAULT 'NO_BET', confidence DOUBLE PRECISION, probability DOUBLE PRECISION,
 odds DOUBLE PRECISION, opening_odds DOUBLE PRECISION, closing_odds DOUBLE PRECISION, clv DOUBLE PRECISION,
 ev DOUBLE PRECISION, pqi DOUBLE PRECISION, model_version TEXT DEFAULT '2.0-data-validation',
 feature_version TEXT DEFAULT '2.0', result TEXT DEFAULT 'PENDING', profit DOUBLE PRECISION DEFAULT 0,
 payload TEXT NOT NULL, market_key TEXT, fixture_date TEXT, fixture_status TEXT,
 home_score INTEGER, away_score INTEGER, settled_at TEXT, source TEXT DEFAULT 'MANUAL',
 league_id BIGINT, season INTEGER, calibration_bucket TEXT, settlement_checked_at TEXT,
 settlement_state TEXT DEFAULT 'PENDING', settlement_reason TEXT, settlement_retry_count INTEGER DEFAULT 0,
 next_retry_at TEXT, recovery_attempts INTEGER DEFAULT 0, recovered_from_fixture_id BIGINT, last_api_status TEXT
)""",
"""CREATE TABLE IF NOT EXISTS paper_trades (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TEXT NOT NULL,
 fixture_id BIGINT, description TEXT NOT NULL, odds DOUBLE PRECISION NOT NULL,
 stake DOUBLE PRECISION NOT NULL, result TEXT DEFAULT 'PENDING', profit DOUBLE PRECISION DEFAULT 0
)""",
"""CREATE TABLE IF NOT EXISTS app_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS odds_snapshots (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id BIGINT NOT NULL,
 captured_at TEXT NOT NULL, market_key TEXT NOT NULL, odds DOUBLE PRECISION NOT NULL,
 bookmaker TEXT, snapshot_type TEXT DEFAULT 'LIVE'
)""",
"""CREATE TABLE IF NOT EXISTS model_diagnostics (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, prediction_id BIGINT,
 model_name TEXT NOT NULL, predicted_probability DOUBLE PRECISION NOT NULL,
 result INTEGER, league TEXT, market_key TEXT, created_at TEXT NOT NULL
)""",

"""CREATE TABLE IF NOT EXISTS prediction_snapshots (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id BIGINT NOT NULL,
 created_at TEXT NOT NULL, pick TEXT, market_key TEXT, probability DOUBLE PRECISION,
 confidence DOUBLE PRECISION, pqi DOUBLE PRECISION, payload TEXT NOT NULL
)""",
"""CREATE INDEX IF NOT EXISTS idx_prediction_snapshots_fixture ON prediction_snapshots(fixture_id, created_at)""",
"""CREATE UNIQUE INDEX IF NOT EXISTS idx_predictions_fixture_pick ON predictions(fixture_id, pick)""",
"""CREATE INDEX IF NOT EXISTS idx_predictions_date_source ON predictions(fixture_date, source)""",
"""CREATE INDEX IF NOT EXISTS idx_odds_fixture_market ON odds_snapshots(fixture_id, market_key, captured_at)""",
"""CREATE TABLE IF NOT EXISTS decision_records (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id BIGINT NOT NULL UNIQUE,
 business_date TEXT, fixture_date TEXT, fixture_status TEXT, league TEXT, home_team TEXT, away_team TEXT,
 final_tier TEXT NOT NULL DEFAULT 'NO_BET', final_label TEXT NOT NULL DEFAULT 'NO BET', published INTEGER NOT NULL DEFAULT 0,
 best_market_key TEXT, best_market_label TEXT, best_market_probability DOUBLE PRECISION, best_market_probability_pct DOUBLE PRECISION,
 recommendation_key TEXT, recommendation_label TEXT, recommendation_probability DOUBLE PRECISION, recommendation_probability_pct DOUBLE PRECISION,
 confidence DOUBLE PRECISION, model_agreement DOUBLE PRECISION, data_quality DOUBLE PRECISION, reliability_grade TEXT,
 reliability_score DOUBLE PRECISION, evidence_strength DOUBLE PRECISION, risk_level TEXT, odds DOUBLE PRECISION, ev DOUBLE PRECISION,
 builder_available INTEGER NOT NULL DEFAULT 0, builder_status TEXT, builder_json TEXT, decision_json TEXT, analysis_json TEXT,
 source_prediction_id BIGINT, source TEXT, engine_version TEXT, updated_at TEXT NOT NULL
)""",
"""CREATE INDEX IF NOT EXISTS idx_decision_records_date_tier ON decision_records(business_date, final_tier)""",
"""CREATE TABLE IF NOT EXISTS automation_runs (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 job_name TEXT NOT NULL, trigger_type TEXT NOT NULL, started_at TEXT NOT NULL,
 finished_at TEXT, status TEXT NOT NULL DEFAULT 'RUNNING', summary TEXT
)""",
"""CREATE INDEX IF NOT EXISTS idx_automation_runs_started ON automation_runs(started_at)""",

"""CREATE TABLE IF NOT EXISTS performance_builder_settlements (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id BIGINT NOT NULL, template_code TEXT NOT NULL,
 portfolio_rank INTEGER, builder_dna TEXT, builder_label TEXT, result TEXT NOT NULL, odds DOUBLE PRECISION,
 ev DOUBLE PRECISION, builder_quality DOUBLE PRECISION, risk_level TEXT, profit DOUBLE PRECISION, stake DOUBLE PRECISION DEFAULT 0,
 settled_at TEXT, UNIQUE(fixture_id,template_code)
)""",
"""CREATE TABLE IF NOT EXISTS performance_rollups (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dimension_type TEXT NOT NULL, dimension_value TEXT NOT NULL, period_key TEXT NOT NULL,
 sample INTEGER NOT NULL DEFAULT 0, wins INTEGER NOT NULL DEFAULT 0, losses INTEGER NOT NULL DEFAULT 0, voids INTEGER NOT NULL DEFAULT 0,
 accuracy DOUBLE PRECISION DEFAULT 0, profit DOUBLE PRECISION DEFAULT 0, stake DOUBLE PRECISION DEFAULT 0, roi DOUBLE PRECISION DEFAULT 0,
 yield_pct DOUBLE PRECISION DEFAULT 0, avg_odds DOUBLE PRECISION DEFAULT 0, avg_ev DOUBLE PRECISION DEFAULT 0, avg_clv DOUBLE PRECISION DEFAULT 0,
 extra_json TEXT, updated_at TEXT NOT NULL, UNIQUE(dimension_type,dimension_value,period_key)
)""",
"""CREATE TABLE IF NOT EXISTS performance_ai_score (
 id INTEGER PRIMARY KEY, score DOUBLE PRECISION DEFAULT 0, grade TEXT DEFAULT 'D', sample INTEGER DEFAULT 0,
 accuracy_component DOUBLE PRECISION DEFAULT 0, roi_component DOUBLE PRECISION DEFAULT 0, yield_component DOUBLE PRECISION DEFAULT 0,
 clv_component DOUBLE PRECISION DEFAULT 0, decision_component DOUBLE PRECISION DEFAULT 0, builder_component DOUBLE PRECISION DEFAULT 0,
 consistency_component DOUBLE PRECISION DEFAULT 0, updated_at TEXT NOT NULL
)""",
"""CREATE TABLE IF NOT EXISTS performance_insights (
 id INTEGER PRIMARY KEY, kind TEXT, title TEXT, message TEXT, created_at TEXT NOT NULL
)""",
"""CREATE TABLE IF NOT EXISTS market_score_snapshots (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id BIGINT NOT NULL, market_key TEXT NOT NULL,
 market_rank INTEGER, raw_probability DOUBLE PRECISION, calibrated_probability DOUBLE PRECISION,
 interval_low DOUBLE PRECISION, interval_high DOUBLE PRECISION, decision_score DOUBLE PRECISION,
 selected INTEGER DEFAULT 0, components_json TEXT, explanation_json TEXT, created_at TEXT NOT NULL
)""",
"""CREATE INDEX IF NOT EXISTS idx_market_score_fixture ON market_score_snapshots(fixture_id, created_at)""",
"""CREATE TABLE IF NOT EXISTS decision_traces (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fixture_id BIGINT NOT NULL, business_date TEXT,
 final_market_key TEXT, final_tier TEXT, trace_json TEXT NOT NULL, engine_version TEXT, created_at TEXT NOT NULL
)""",
"""CREATE INDEX IF NOT EXISTS idx_decision_trace_fixture ON decision_traces(fixture_id, created_at)""",
 ]

class Store:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url
        self.engine: Engine = create_engine(database_url, pool_pre_ping=True, future=True)
        self._init()
        bootstrap_database(self.engine)
        self._metadata = MetaData()
        self._predictions = Table("predictions", self._metadata, autoload_with=self.engine)
        self._decision_snapshots = DecisionSnapshotService()
        self.rebuild_decision_records_from_predictions()
        self.refresh_performance_intelligence()

    def _init(self) -> None:
        # SQLite does not support GENERATED BY DEFAULT AS IDENTITY.
        if self.database_url.startswith("sqlite"):
            schema = [s.replace("INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT") for s in SCHEMA]
        else:
            schema = SCHEMA
        # Create base schema in a clean transaction. Never catch a database error
        # inside an active PostgreSQL transaction: doing so leaves the transaction
        # aborted and causes every later statement to fail with
        # InFailedSqlTransaction.
        with self.engine.begin() as conn:
            for statement in schema:
                conn.execute(text(statement))

        # Additive migration, guarded by schema inspection rather than relying on
        # an exception from ALTER TABLE. This is safe on PostgreSQL and SQLite.
        columns = {column["name"] for column in inspect(self.engine).get_columns("predictions")}
        additive_columns = {
            "settlement_checked_at": "TEXT",
            "settlement_state": "TEXT DEFAULT 'PENDING'",
            "settlement_reason": "TEXT",
            "settlement_retry_count": "INTEGER DEFAULT 0",
            "next_retry_at": "TEXT",
            "recovery_attempts": "INTEGER DEFAULT 0",
            "recovered_from_fixture_id": "BIGINT",
            "last_api_status": "TEXT",
            "settlement_eligible": "INTEGER DEFAULT 1",
        }
        for column_name, column_type in additive_columns.items():
            if column_name not in columns:
                with self.engine.begin() as conn:
                    conn.execute(text(f"ALTER TABLE predictions ADD COLUMN {column_name} {column_type}"))

        # Reconcile legacy observations. NO BET/MONITOR rows are analytical
        # snapshots, not wagers, and must never inflate the settlement queue.
        with self.engine.begin() as conn:
            conn.execute(text("""
                UPDATE predictions
                SET settlement_eligible = CASE
                    WHEN UPPER(COALESCE(pick_role,'')) IN ('NO_BET','NO PICK','NO_PICK','MONITOR','WATCH')
                      OR UPPER(REPLACE(COALESCE(pick,''),'_',' ')) IN ('NO BET','NO PICK')
                      OR UPPER(COALESCE(market_key,'')) = 'NO_BET'
                    THEN 0 ELSE COALESCE(settlement_eligible,1) END
            """))
            conn.execute(text("""
                UPDATE predictions
                SET settlement_state='NOT_APPLICABLE', next_retry_at=NULL
                WHERE result='PENDING' AND COALESCE(settlement_eligible,1)=0
            """))

        # Seed defaults in a separate transaction so a migration issue can never
        # poison application startup settings.
        with self.engine.begin() as conn:
            for key, value in DEFAULT_ADMIN_SETTINGS.items():
                conn.execute(
                    text("INSERT INTO app_settings(key,value) VALUES (:k,:v) ON CONFLICT(key) DO NOTHING"),
                    {"k": key, "v": json.dumps(value)},
                )

    def _rows(self, sql: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]:
        with self.engine.connect() as conn:
            return [dict(r._mapping) for r in conn.execute(text(sql), params or {})]

    def save_prediction(self, row: dict[str, Any]) -> None:
        payload = json.dumps(row, ensure_ascii=False, default=str)
        now = datetime.now(timezone.utc).isoformat()
        params = {
            "fixture_id": row.get("fixture_id"), "created_at": now, "league": row.get("league"),
            "home_team": row.get("home_team"), "away_team": row.get("away_team"), "pick": row.get("pick"),
            "pick_role": row.get("pick_role", "NO_BET"), "confidence": row.get("confidence"),
            "probability": row.get("probability"), "odds": row.get("odds"), "opening_odds": row.get("odds"),
            "ev": row.get("ev"), "pqi": row.get("pqi"), "payload": payload, "market_key": row.get("market_key"),
            "fixture_date": row.get("fixture_date"), "fixture_status": row.get("fixture_status"),
            "source": row.get("source", "MANUAL"), "league_id": row.get("league_id"), "season": row.get("season"),
            "calibration_bucket": self._bucket(row.get("probability")),
            "settlement_eligible": 1 if row.get("settlement_eligible", True) else 0,
            "settlement_state": "PENDING" if row.get("settlement_eligible", True) else "NOT_APPLICABLE",
            "settlement_reason": None if row.get("settlement_eligible", True) else "Observasi model; bukan rekomendasi settlement",
        }
        sql = """INSERT INTO predictions
        (fixture_id,created_at,league,home_team,away_team,pick,pick_role,confidence,probability,odds,opening_odds,ev,pqi,payload,market_key,fixture_date,fixture_status,source,league_id,season,calibration_bucket,settlement_eligible,settlement_state,settlement_reason)
        VALUES (:fixture_id,:created_at,:league,:home_team,:away_team,:pick,:pick_role,:confidence,:probability,:odds,:opening_odds,:ev,:pqi,:payload,:market_key,:fixture_date,:fixture_status,:source,:league_id,:season,:calibration_bucket,:settlement_eligible,:settlement_state,:settlement_reason)
        ON CONFLICT(fixture_id,pick) DO UPDATE SET
        created_at=excluded.created_at,pick_role=excluded.pick_role,confidence=excluded.confidence,probability=excluded.probability,
        odds=excluded.odds,ev=excluded.ev,pqi=excluded.pqi,payload=excluded.payload,market_key=excluded.market_key,
        fixture_date=excluded.fixture_date,fixture_status=excluded.fixture_status,source=excluded.source,
        settlement_eligible=excluded.settlement_eligible,
        settlement_state=CASE
          WHEN predictions.result='PENDING' AND excluded.settlement_eligible=0 THEN 'NOT_APPLICABLE'
          WHEN predictions.result='PENDING' AND excluded.settlement_eligible=1 AND predictions.settlement_state='NOT_APPLICABLE' THEN 'PENDING'
          ELSE predictions.settlement_state END"""
        with self.engine.begin() as conn:
            conn.execute(text(sql), params)
            # A fixture may be rescanned with a different market. Keep historical
            # snapshots, but only the newest decision remains settlement-eligible.
            conn.execute(text("""
                UPDATE predictions
                SET settlement_eligible=0,
                    settlement_state='SUPERSEDED',
                    settlement_reason='Digantikan snapshot keputusan terbaru',
                    next_retry_at=NULL
                WHERE fixture_id=:fixture_id
                  AND result='PENDING'
                  AND pick<>:pick
                  AND COALESCE(settlement_eligible,1)=1
            """), {"fixture_id": params["fixture_id"], "pick": params["pick"]})
            conn.execute(text("""INSERT INTO prediction_snapshots
                (fixture_id,created_at,pick,market_key,probability,confidence,pqi,payload)
                VALUES (:fixture_id,:created_at,:pick,:market_key,:probability,:confidence,:pqi,:payload)"""), params)
        self.sync_decision_record_for_fixture(int(row.get("fixture_id") or 0))

    @staticmethod
    def _bucket(probability: Any) -> str | None:
        if probability is None: return None
        p=float(probability)*100 if float(probability)<=1 else float(probability)
        lo=int(p//10)*10
        return f"{lo}-{min(100,lo+9)}"

    def recent_predictions(self, limit: int = 100) -> list[dict[str, Any]]:
        return self._rows("SELECT * FROM predictions ORDER BY id DESC LIMIT :n", {"n": limit})

    def prediction_history(
        self,
        *,
        date_from: str | None = None,
        date_to: str | None = None,
        result: str | None = None,
        fixture_status: str | None = None,
        search: str | None = None,
        limit: int = 500,
    ) -> list[dict[str, Any]]:
        clauses = []
        params: dict[str, Any] = {"n": max(1, min(int(limit), 2000))}
        if date_from:
            clauses.append("SUBSTR(fixture_date, 1, 10) >= :date_from")
            params["date_from"] = date_from
        if date_to:
            clauses.append("SUBSTR(fixture_date, 1, 10) <= :date_to")
            params["date_to"] = date_to
        if result and result.upper() != "ALL":
            clauses.append("result = :result")
            params["result"] = result.upper()
        if fixture_status and fixture_status.upper() != "ALL":
            clauses.append("fixture_status = :fixture_status")
            params["fixture_status"] = fixture_status.upper()
        if search:
            clauses.append("(LOWER(home_team) LIKE :search OR LOWER(away_team) LIKE :search OR LOWER(league) LIKE :search OR CAST(fixture_id AS TEXT) LIKE :search)")
            params["search"] = f"%{search.strip().lower()}%"
        where = f" WHERE {' AND '.join(clauses)}" if clauses else ""
        sql = f"SELECT * FROM predictions{where} ORDER BY fixture_date DESC, id DESC LIMIT :n"
        return self._rows(sql, params)

    def prediction_history_summary(self) -> dict[str, Any]:
        # Previous recovery query used:
        # SUBSTR(fixture_date, 1, 10) < CAST(CURRENT_DATE AS TEXT)
        # V8.0.2 supplies the WITA date as a bind parameter so PostgreSQL and
        # SQLite classify overdue fixtures using the same business day.
        # The business day follows WITA (UTC+8), not the database server clock.
        today_wita = datetime.now(ZoneInfo("Asia/Makassar")).date().isoformat()
        rows = self._rows("""SELECT
            COUNT(*) AS total,
            SUM(CASE WHEN result='PENDING' AND COALESCE(settlement_eligible,1)=1 THEN 1 ELSE 0 END) AS pending,
            SUM(CASE WHEN result='PENDING' AND COALESCE(settlement_eligible,1)=0 THEN 1 ELSE 0 END) AS observations,
            SUM(CASE WHEN result='WIN' THEN 1 ELSE 0 END) AS wins,
            SUM(CASE WHEN result='LOSS' THEN 1 ELSE 0 END) AS losses,
            SUM(CASE WHEN result='VOID' THEN 1 ELSE 0 END) AS voids,
            SUM(CASE WHEN result='PENDING' AND COALESCE(settlement_eligible,1)=1 AND SUBSTR(fixture_date, 1, 10) < :today AND COALESCE(settlement_state,'PENDING') <> 'NEEDS_INVESTIGATION' THEN 1 ELSE 0 END) AS overdue_pending,
            SUM(CASE WHEN result='PENDING' AND COALESCE(settlement_eligible,1)=1 AND settlement_state='NEEDS_INVESTIGATION' THEN 1 ELSE 0 END) AS needs_investigation
            FROM predictions""", {"today": today_wita})
        return rows[0] if rows else {"total":0,"pending":0,"wins":0,"losses":0,"voids":0,"overdue_pending":0,"needs_investigation":0}

    def predictions_for_date(self, fixture_date: str, *, source: str | None = None) -> list[dict[str, Any]]:
        sql="SELECT * FROM predictions WHERE fixture_date=:d"; p={"d":fixture_date}
        if source: sql += " AND source=:s"; p["s"]=source
        return self._rows(sql+" ORDER BY id DESC",p)

    def pending_predictions_for_date(self, fixture_date: str) -> list[dict[str, Any]]:
        return self._rows("SELECT * FROM predictions WHERE fixture_date=:d AND source='SCANNER' AND result='PENDING'",{"d":fixture_date})

    def settle_prediction_by_fixture(self, fixture_id: int, market_key: str, result: str, *, fixture_status: str, home_score: int|None, away_score: int|None) -> None:
        now=datetime.now(timezone.utc).isoformat(); result=result.upper()
        rows=self._rows("SELECT id,odds FROM predictions WHERE fixture_id=:f AND market_key=:m AND result='PENDING' AND COALESCE(settlement_eligible,1)=1",{"f":fixture_id,"m":market_key})
        with self.engine.begin() as conn:
            for row in rows:
                odds=float(row.get("odds") or 1.0); profit=(odds-1) if result=="WIN" else (-1 if result=="LOSS" else 0)
                conn.execute(text("UPDATE predictions SET result=:r,profit=:p,fixture_status=:s,home_score=:h,away_score=:a,settled_at=:t WHERE id=:id"),{"r":result,"p":profit,"s":fixture_status,"h":home_score,"a":away_score,"t":now,"id":row["id"]})
        if rows:
            self.refresh_performance_intelligence()

    def settle_prediction(self, prediction_id: int, result: str) -> None:
        rows=self._rows("SELECT odds FROM predictions WHERE id=:id",{"id":prediction_id})
        if not rows:return
        odds=float(rows[0].get("odds") or 1); result=result.upper(); profit=(odds-1) if result=="WIN" else (-1 if result=="LOSS" else 0)
        with self.engine.begin() as conn: conn.execute(text("UPDATE predictions SET result=:r,profit=:p,settled_at=:t,settlement_state='SETTLED' WHERE id=:id"),{"r":result,"p":profit,"t":datetime.now(timezone.utc).isoformat(),"id":prediction_id})
        self.refresh_performance_intelligence()

    def historical_accuracy(self, league: str|None=None) -> float:
        sql="SELECT result FROM predictions WHERE result IN ('WIN','LOSS')"; p={}
        if league: sql+=" AND league=:l";p["l"]=league
        rows=self._rows(sql,p); return sum(r["result"]=="WIN" for r in rows)/len(rows) if rows else .55

    def save_odds_snapshot(self, fixture_id: int, rows: list[dict[str, Any]], snapshot_type: str="LIVE") -> None:
        now=datetime.now(timezone.utc).isoformat()
        with self.engine.begin() as conn:
            for row in rows:
                if row.get("odds"):
                    conn.execute(text("INSERT INTO odds_snapshots(fixture_id,captured_at,market_key,odds,bookmaker,snapshot_type) VALUES (:f,:t,:m,:o,:b,:s)"),{"f":fixture_id,"t":now,"m":row["key"],"o":row["odds"],"b":row.get("bookmaker"),"s":snapshot_type})
                    conn.execute(text("UPDATE predictions SET closing_odds=:o, clv=CASE WHEN opening_odds IS NOT NULL THEN opening_odds/:o-1 ELSE NULL END WHERE fixture_id=:f AND market_key=:m AND result='PENDING'"),{"o":row["odds"],"f":fixture_id,"m":row["key"]})


    def upsert_decision_record(self, record: dict[str, Any]) -> None:
        if not int(record.get("fixture_id") or 0):
            return
        params = dict(record)
        params["published"] = 1 if record.get("published") else 0
        params["builder_available"] = 1 if record.get("builder_available") else 0
        params["builder_json"] = json.dumps(record.get("builder") or {}, ensure_ascii=False, default=str)
        params["decision_json"] = json.dumps(record.get("decision") or {}, ensure_ascii=False, default=str)
        params["analysis_json"] = json.dumps(record.get("analysis") or {}, ensure_ascii=False, default=str)
        sql = """INSERT INTO decision_records (
            fixture_id,business_date,fixture_date,fixture_status,league,home_team,away_team,final_tier,final_label,published,
            best_market_key,best_market_label,best_market_probability,best_market_probability_pct,recommendation_key,recommendation_label,
            recommendation_probability,recommendation_probability_pct,confidence,model_agreement,data_quality,reliability_grade,reliability_score,
            evidence_strength,risk_level,odds,ev,builder_available,builder_status,builder_json,decision_json,analysis_json,
            source_prediction_id,source,engine_version,updated_at)
            VALUES (:fixture_id,:business_date,:fixture_date,:fixture_status,:league,:home_team,:away_team,:final_tier,:final_label,:published,
            :best_market_key,:best_market_label,:best_market_probability,:best_market_probability_pct,:recommendation_key,:recommendation_label,
            :recommendation_probability,:recommendation_probability_pct,:confidence,:model_agreement,:data_quality,:reliability_grade,:reliability_score,
            :evidence_strength,:risk_level,:odds,:ev,:builder_available,:builder_status,:builder_json,:decision_json,:analysis_json,
            :source_prediction_id,:source,:engine_version,:updated_at)
            ON CONFLICT(fixture_id) DO UPDATE SET
            business_date=excluded.business_date,fixture_date=excluded.fixture_date,fixture_status=excluded.fixture_status,league=excluded.league,
            home_team=excluded.home_team,away_team=excluded.away_team,final_tier=excluded.final_tier,final_label=excluded.final_label,
            published=excluded.published,best_market_key=excluded.best_market_key,best_market_label=excluded.best_market_label,
            best_market_probability=excluded.best_market_probability,best_market_probability_pct=excluded.best_market_probability_pct,
            recommendation_key=excluded.recommendation_key,recommendation_label=excluded.recommendation_label,
            recommendation_probability=excluded.recommendation_probability,recommendation_probability_pct=excluded.recommendation_probability_pct,
            confidence=excluded.confidence,model_agreement=excluded.model_agreement,data_quality=excluded.data_quality,
            reliability_grade=excluded.reliability_grade,reliability_score=excluded.reliability_score,evidence_strength=excluded.evidence_strength,
            risk_level=excluded.risk_level,odds=excluded.odds,ev=excluded.ev,builder_available=excluded.builder_available,
            builder_status=excluded.builder_status,builder_json=excluded.builder_json,decision_json=excluded.decision_json,
            analysis_json=excluded.analysis_json,source_prediction_id=excluded.source_prediction_id,source=excluded.source,
            engine_version=excluded.engine_version,updated_at=excluded.updated_at"""
        with self.engine.begin() as conn:
            conn.execute(text(sql), params)

    def sync_decision_record_for_fixture(self, fixture_id: int) -> None:
        if not fixture_id:
            return
        row = self.latest_prediction_by_fixture(fixture_id)
        if not row:
            return
        record = self._decision_snapshots.from_prediction_row(row)
        if record:
            self.upsert_decision_record(record)

    def rebuild_decision_records_from_predictions(self) -> int:
        rows = self._rows("""SELECT p.* FROM predictions p JOIN (
            SELECT fixture_id, MAX(id) AS max_id FROM predictions GROUP BY fixture_id
        ) latest ON latest.max_id=p.id ORDER BY p.id DESC""")
        count = 0
        for row in rows:
            record = DecisionSnapshotService().from_prediction_row(row)
            if record:
                self.upsert_decision_record(record)
                count += 1
        return count

    def decision_records_for_date(self, business_date: str, limit: int = 2000) -> list[dict[str, Any]]:
        rows = self._rows("""SELECT * FROM decision_records WHERE business_date=:d
            ORDER BY CASE final_tier WHEN 'ELITE_PICK' THEN 5 WHEN 'STRONG_PICK' THEN 4 WHEN 'PICK' THEN 3 WHEN 'MONITOR' THEN 2 ELSE 1 END DESC,
            data_quality DESC, confidence DESC LIMIT :n""", {"d": business_date, "n": limit})
        for row in rows:
            for source, target in (("builder_json", "builder"), ("decision_json", "decision"), ("analysis_json", "analysis")):
                try: row[target] = json.loads(row.get(source) or "{}")
                except (TypeError, ValueError): row[target] = {}
            row["published"] = bool(row.get("published"))
            row["builder_available"] = bool(row.get("builder_available"))
        return rows

    def latest_decision_record(self, fixture_id: int) -> dict[str, Any] | None:
        rows = self._rows("SELECT * FROM decision_records WHERE fixture_id=:f LIMIT 1", {"f": fixture_id})
        if not rows:
            return None
        row = rows[0]
        for source, target in (("builder_json", "builder"), ("decision_json", "decision"), ("analysis_json", "analysis")):
            try: row[target] = json.loads(row.get(source) or "{}")
            except (TypeError, ValueError): row[target] = {}
        row["published"] = bool(row.get("published")); row["builder_available"] = bool(row.get("builder_available"))
        return row

    def latest_market_odds(self, fixture_id: int, market_key: str) -> float|None:
        rows=self._rows("SELECT odds FROM odds_snapshots WHERE fixture_id=:f AND market_key=:m ORDER BY id DESC LIMIT 1",{"f":fixture_id,"m":market_key})
        return float(rows[0]["odds"]) if rows else None

    def settings(self)->dict[str,Any]:
        return {r["key"]:json.loads(r["value"]) for r in self._rows("SELECT key,value FROM app_settings")}
    def update_settings(self,values:dict[str,Any])->None:
        with self.engine.begin() as conn:
            for k,v in values.items():
                if k in DEFAULT_ADMIN_SETTINGS: conn.execute(text("INSERT INTO app_settings(key,value) VALUES (:k,:v) ON CONFLICT(key) DO UPDATE SET value=excluded.value"),{"k":k,"v":json.dumps(v)})
    def add_trade(self,fixture_id:int,description:str,odds:float,stake:float)->None:
        with self.engine.begin() as conn: conn.execute(text("INSERT INTO paper_trades(created_at,fixture_id,description,odds,stake) VALUES (:t,:f,:d,:o,:s)"),{"t":datetime.now(timezone.utc).isoformat(),"f":fixture_id,"d":description,"o":odds,"s":stake})
    def trades(self,limit:int=200)->list[dict[str,Any]]: return self._rows("SELECT * FROM paper_trades ORDER BY id DESC LIMIT :n",{"n":limit})
    def settle_trade(self,trade_id:int,result:str)->None:
        rows=self._rows("SELECT odds,stake FROM paper_trades WHERE id=:id",{"id":trade_id})
        if not rows:return
        r=rows[0]; result=result.upper(); profit=(r["odds"]-1)*r["stake"] if result=="WIN" else (-r["stake"] if result=="LOSS" else 0)
        with self.engine.begin() as conn: conn.execute(text("UPDATE paper_trades SET result=:r,profit=:p WHERE id=:id"),{"r":result,"p":profit,"id":trade_id})

    def performance_breakdown(self) -> dict[str, list[dict[str, Any]]]:
        base="""SELECT {group_col} AS name, COUNT(*) AS samples,
        SUM(CASE WHEN result='WIN' THEN 1 ELSE 0 END) AS wins,
        AVG(CASE WHEN result='WIN' THEN 1.0 WHEN result='LOSS' THEN 0.0 END) AS accuracy,
        SUM(profit) AS profit, AVG(clv) AS avg_clv
        FROM predictions WHERE result IN ('WIN','LOSS') GROUP BY {group_col} ORDER BY samples DESC"""
        return {"by_league":self._rows(base.format(group_col="league")),"by_market":self._rows(base.format(group_col="market_key"))}



    def refresh_performance_intelligence(self) -> None:
        """Materialize settlement-backed performance analytics.

        Failures are isolated from core prediction/settlement transactions so a
        reporting issue can never block settlement.
        """
        try:
            from app.services.performance_intelligence import PerformanceIntelligence
            PerformanceIntelligence(self).rebuild()
        except Exception:
            # Performance is a derived warehouse; the next startup/settlement run
            # will rebuild it from authoritative settled rows.
            pass


    def market_performance_snapshot(self) -> dict[str, dict[str, Any]]:
        """Return settlement-backed market performance for ranking.

        Prefer 30D when it has a meaningful sample; otherwise fall back to ALL.
        This is read-only and never recalculates performance inside the request.
        """
        rows = self._rows("""SELECT * FROM performance_rollups
            WHERE dimension_type='MARKET' AND period_key IN ('30D','ALL')""")
        grouped: dict[str, dict[str, dict[str, Any]]] = {}
        for row in rows:
            key = str(row.get("dimension_value") or "")
            grouped.setdefault(key, {})[str(row.get("period_key") or "ALL")] = row
        out: dict[str, dict[str, Any]] = {}
        for key, periods in grouped.items():
            recent = periods.get("30D") or {}
            all_time = periods.get("ALL") or {}
            if int(recent.get("sample") or 0) >= 10:
                chosen = dict(recent)
                chosen["performance_period"] = "30D"
            else:
                chosen = dict(all_time or recent)
                chosen["performance_period"] = "ALL" if all_time else "30D"
            out[key] = chosen
        return out

    def market_calibration_snapshot(self, market_probabilities: dict[str, float]) -> dict[str, dict[str, Any]]:
        """Settlement-backed empirical calibration near each current probability.

        Only WIN/LOSS rows participate. We use a ±10 percentage-point local
        window and cap the lookback to keep request cost predictable.
        """
        if not market_probabilities:
            return {}
        rows = self._rows("""SELECT market_key, probability, result
            FROM predictions
            WHERE result IN ('WIN','LOSS') AND market_key IS NOT NULL AND probability IS NOT NULL
            ORDER BY id DESC LIMIT 12000""")
        out: dict[str, dict[str, Any]] = {}
        for key, target in market_probabilities.items():
            try:
                target_p = float(target)
            except (TypeError, ValueError):
                continue
            samples = [r for r in rows if str(r.get("market_key") or "") == str(key)
                       and abs(float(r.get("probability") or 0) - target_p) <= 0.10]
            wins = sum(1 for r in samples if str(r.get("result") or "").upper() == "WIN")
            out[str(key)] = {
                "sample": len(samples), "wins": wins, "losses": len(samples)-wins,
                "target_probability": target_p,
            }
        return out

    def save_decision_intelligence_trace(
        self, fixture_id: int, business_date: str, ranked_markets: list[dict[str, Any]],
        final_market: dict[str, Any] | None, final_tier: str, *, engine_version: str = "14.0"
    ) -> None:
        """Persist an auditable V14 market competition trace.

        Trace persistence is derived analytics and isolated from prediction
        settlement. Failure here must never invalidate a recommendation.
        """
        try:
            now = datetime.now(timezone.utc).isoformat()
            final_key = str((final_market or {}).get("key") or "") or None
            trace = {
                "fixture_id": int(fixture_id),
                "business_date": business_date,
                "final_market_key": final_key,
                "final_tier": final_tier,
                "markets": [
                    {
                        "key": r.get("key"), "label": r.get("label"), "rank": r.get("market_rank"),
                        "raw_probability": r.get("raw_probability"),
                        "calibrated_probability": r.get("calibrated_probability"),
                        "interval_low": r.get("confidence_interval_low"),
                        "interval_high": r.get("confidence_interval_high"),
                        "score": r.get("market_intelligence_score"),
                        "components": r.get("market_intelligence_components"),
                        "relationship": r.get("market_relationship"),
                        "reasons": r.get("market_intelligence_reasons"),
                    } for r in ranked_markets
                ],
            }
            with self.engine.begin() as conn:
                # Keep only the latest trace snapshot for a fixture in the market score table.
                conn.execute(text("DELETE FROM market_score_snapshots WHERE fixture_id=:f"), {"f": int(fixture_id)})
                for r in ranked_markets:
                    conn.execute(text("""INSERT INTO market_score_snapshots
                        (fixture_id,market_key,market_rank,raw_probability,calibrated_probability,interval_low,interval_high,
                         decision_score,selected,components_json,explanation_json,created_at)
                        VALUES (:f,:k,:rank,:raw,:cal,:lo,:hi,:score,:sel,:comp,:exp,:created)"""), {
                        "f": int(fixture_id), "k": str(r.get("key") or ""), "rank": int(r.get("market_rank") or 0),
                        "raw": r.get("raw_probability"), "cal": r.get("calibrated_probability"),
                        "lo": r.get("confidence_interval_low"), "hi": r.get("confidence_interval_high"),
                        "score": r.get("market_intelligence_score"), "sel": 1 if str(r.get("key") or "") == final_key else 0,
                        "comp": json.dumps(r.get("market_intelligence_components") or {}, ensure_ascii=False, default=str),
                        "exp": json.dumps(r.get("market_intelligence_reasons") or [], ensure_ascii=False, default=str),
                        "created": now,
                    })
                conn.execute(text("""INSERT INTO decision_traces
                    (fixture_id,business_date,final_market_key,final_tier,trace_json,engine_version,created_at)
                    VALUES (:f,:d,:k,:tier,:trace,:ver,:created)"""), {
                    "f": int(fixture_id), "d": business_date or None, "k": final_key, "tier": final_tier,
                    "trace": json.dumps(trace, ensure_ascii=False, default=str), "ver": engine_version, "created": now,
                })
        except Exception:
            pass

    def latest_decision_trace(self, fixture_id: int) -> dict[str, Any] | None:
        rows = self._rows("SELECT * FROM decision_traces WHERE fixture_id=:f ORDER BY id DESC LIMIT 1", {"f": int(fixture_id)})
        if not rows:
            return None
        row = dict(rows[0])
        try:
            row["trace"] = json.loads(row.get("trace_json") or "{}")
        except Exception:
            row["trace"] = {}
        return row

    def decision_market_counts_for_date(self, business_date: str) -> dict[str, int]:
        """Published recommendation distribution used only as a small diversity tie-breaker."""
        rows = self._rows("""SELECT recommendation_key AS market_key, COUNT(*) AS n
            FROM decision_records
            WHERE business_date=:d AND published=1 AND recommendation_key IS NOT NULL
            GROUP BY recommendation_key""", {"d": business_date})
        return {str(row.get("market_key") or ""): int(row.get("n") or 0) for row in rows if row.get("market_key")}

    def performance_intelligence_dashboard(self) -> dict[str, Any]:
        from app.services.performance_intelligence import PerformanceIntelligence
        return PerformanceIntelligence(self).dashboard()


    def latest_prediction_by_fixture(self, fixture_id: int) -> dict[str, Any] | None:
        """Return the newest stored decision for a fixture without calling external APIs."""
        rows = self._rows(
            "SELECT * FROM predictions WHERE fixture_id=:fixture_id ORDER BY id DESC LIMIT 1",
            {"fixture_id": int(fixture_id)},
        )
        return rows[0] if rows else None

    def stored_matches_for_date(self, fixture_date: str, limit: int = 1000) -> list[dict[str, Any]]:
        """Read-only match catalogue backed entirely by stored predictions."""
        return self._rows(
            """SELECT * FROM predictions
               WHERE SUBSTR(COALESCE(fixture_date, created_at),1,10)=:fixture_date
               ORDER BY league ASC, home_team ASC, id DESC LIMIT :n""",
            {"fixture_date": fixture_date, "n": max(1, min(int(limit), 2000))},
        )

    def prediction_by_id(self, prediction_id: int) -> dict[str, Any] | None:
        rows=self._rows("SELECT * FROM predictions WHERE id=:id",{"id":prediction_id})
        return rows[0] if rows else None

    def snapshots_for_fixture(self, fixture_id: int, limit: int=30) -> list[dict[str, Any]]:
        return self._rows("SELECT * FROM prediction_snapshots WHERE fixture_id=:f ORDER BY id DESC LIMIT :n",{"f":fixture_id,"n":limit})

    def database_status(self) -> dict[str, Any]:
        return database_inventory(self.engine)


    def settlement_queue_rows(self) -> list[dict[str, Any]]:
        """Return every pending prediction for the unified queue service.

        No source, retry or date filter is applied here. Classification belongs to
        SettlementQueueService so every UI and engine reads the same population.
        """
        return self._rows("""SELECT * FROM predictions
            WHERE result='PENDING' AND COALESCE(settlement_eligible,1)=1 AND fixture_id IS NOT NULL
            ORDER BY SUBSTR(fixture_date,1,10) ASC, id ASC""")

    def pending_predictions_by_fixture(self, fixture_id: int) -> list[dict[str, Any]]:
        return self._rows("""SELECT * FROM predictions
            WHERE result='PENDING' AND COALESCE(settlement_eligible,1)=1 AND fixture_id=:fixture_id ORDER BY id ASC""",
            {"fixture_id": int(fixture_id)})

    def settlement_result_totals(self) -> dict[str, int]:
        rows = self._rows("""SELECT
            SUM(CASE WHEN result='WIN' THEN 1 ELSE 0 END) AS wins,
            SUM(CASE WHEN result='LOSS' THEN 1 ELSE 0 END) AS losses,
            SUM(CASE WHEN result='VOID' THEN 1 ELSE 0 END) AS voids,
            SUM(CASE WHEN result IN ('WIN','LOSS','VOID') THEN 1 ELSE 0 END) AS settled
            FROM predictions""")
        row = rows[0] if rows else {}
        return {key: int(row.get(key) or 0) for key in ("wins","losses","voids","settled")}

    def pending_scanner_predictions(self, limit: int = 1000, *, overdue_only: bool = False) -> list[dict[str, Any]]:
        """Return one unified queue of pending predictions.

        Candidate selection deliberately depends only on the prediction still being
        PENDING, having a fixture ID, and not having been explicitly isolated for
        manual investigation.  ``source``, ``next_retry_at`` and retry metadata are
        diagnostics only; they must never hide old predictions from settlement.

        Overdue mode narrows this same queue to fixture dates before today's WITA
        date.  Within either mode the oldest fixture date is processed first, while
        ``settlement_checked_at`` rotates repeatedly non-final fixtures behind rows
        that have not yet been checked.
        """
        today_wita = datetime.now(ZoneInfo("Asia/Makassar")).date().isoformat()
        overdue_clause = "AND SUBSTR(fixture_date, 1, 10) < :today" if overdue_only else ""
        return self._rows(
            f"""SELECT * FROM predictions
               WHERE result='PENDING'
                 AND COALESCE(settlement_eligible,1)=1
                 AND fixture_id IS NOT NULL
                 AND COALESCE(settlement_state, 'PENDING') <> 'NEEDS_INVESTIGATION'
                 {overdue_clause}
               ORDER BY
                 CASE WHEN SUBSTR(fixture_date, 1, 10) < :today THEN 0 ELSE 1 END,
                 SUBSTR(fixture_date, 1, 10) ASC,
                 CASE WHEN settlement_checked_at IS NULL THEN 0 ELSE 1 END,
                 settlement_checked_at ASC,
                 id ASC
               LIMIT :n""",
            {"n": limit, "today": today_wita},
        )

    def overdue_pending_count(self) -> int:
        today_wita = datetime.now(ZoneInfo("Asia/Makassar")).date().isoformat()
        rows = self._rows(
            """SELECT COUNT(*) AS count FROM predictions
               WHERE result='PENDING'
                 AND COALESCE(settlement_eligible,1)=1
                 AND fixture_id IS NOT NULL
                 AND (source='SCANNER' OR source IS NULL)
                 AND SUBSTR(fixture_date, 1, 10) < :today
                 AND COALESCE(settlement_state, 'PENDING') <> 'NEEDS_INVESTIGATION'""",
            {"today": today_wita},
        )
        return int(rows[0].get("count") or 0) if rows else 0

    def mark_fixture_settlement_checked(self, fixture_id: int, *, fixture_status: str | None = None) -> None:
        """Mark a pending fixture as checked using SQLAlchemy Core.

        The update dictionary is built in Python, so nullable values never appear
        in a SQL CASE expression and PostgreSQL never has to infer an ambiguous
        bind type. Each call owns its transaction and automatically rolls back on
        failure.
        """
        values: dict[str, Any] = {
            "settlement_checked_at": datetime.now(timezone.utc).isoformat(),
        }
        if fixture_status is not None:
            values["fixture_status"] = str(fixture_status)

        statement = (
            update(self._predictions)
            .where(
                self._predictions.c.fixture_id == int(fixture_id),
                self._predictions.c.result == "PENDING",
            )
            .values(**values)
        )
        with self.engine.begin() as conn:
            conn.execute(statement)

    def record_fixture_settlement_attempt(
        self,
        fixture_id: int,
        *,
        fixture_status: str | None,
        reason: str,
        state: str = "RETRY",
        increment_retry: bool = True,
        increment_recovery: bool = False,
        next_retry_at: str | None = None,
    ) -> int:
        """Persist settlement diagnostics and return the current retry count."""
        values: dict[str, Any] = {
            "settlement_checked_at": datetime.now(timezone.utc).isoformat(),
            "settlement_state": state,
            "settlement_reason": reason,
            "last_api_status": str(fixture_status or "UNKNOWN"),
            "next_retry_at": next_retry_at,
        }
        if fixture_status is not None:
            values["fixture_status"] = str(fixture_status)
        if increment_retry:
            values["settlement_retry_count"] = func.coalesce(self._predictions.c.settlement_retry_count, 0) + 1
        if increment_recovery:
            values["recovery_attempts"] = func.coalesce(self._predictions.c.recovery_attempts, 0) + 1
        statement = (
            update(self._predictions)
            .where(
                self._predictions.c.fixture_id == int(fixture_id),
                self._predictions.c.result == "PENDING",
            )
            .values(**values)
        )
        with self.engine.begin() as conn:
            conn.execute(statement)
            retry = conn.execute(
                select(self._predictions.c.settlement_retry_count)
                .where(self._predictions.c.fixture_id == int(fixture_id), self._predictions.c.result == "PENDING")
                .order_by(self._predictions.c.settlement_retry_count.desc())
                .limit(1)
            ).scalar()
        return int(retry or 0)

    def requeue_investigation(self, limit: int = 1000) -> int:
        """Return isolated pending fixtures to recovery after an engine hotfix."""
        statement = (
            update(self._predictions)
            .where(
                self._predictions.c.result == "PENDING",
                self._predictions.c.settlement_state == "NEEDS_INVESTIGATION",
            )
            .values(
                settlement_state="RECOVERY",
                settlement_reason="Requeued after settlement queue hotfix",
                settlement_retry_count=0,
                next_retry_at=None,
                settlement_checked_at=None,
            )
        )
        with self.engine.begin() as conn:
            result = conn.execute(statement)
        return int(result.rowcount or 0)

    def mark_fixture_needs_investigation(self, fixture_id: int, *, status: str, reason: str) -> None:
        # Investigation is isolated from frequent retries, but it is not abandoned forever.
        # A daily recheck lets late provider corrections settle automatically.
        next_daily_check = (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        self.record_fixture_settlement_attempt(
            fixture_id, fixture_status=status, reason=reason, state="NEEDS_INVESTIGATION",
            increment_retry=False, next_retry_at=next_daily_check,
        )

    def recover_fixture_id(self, old_fixture_id: int, new_fixture_id: int, *, reason: str) -> int:
        """Move pending predictions to a recovered API fixture ID safely."""
        if int(old_fixture_id) == int(new_fixture_id):
            return 0
        updated = 0
        with self.engine.begin() as conn:
            old_rows = conn.execute(
                select(self._predictions.c.id, self._predictions.c.pick)
                .where(self._predictions.c.fixture_id == int(old_fixture_id), self._predictions.c.result == "PENDING")
                .with_for_update()
            ).mappings().all()
            for row in old_rows:
                duplicate = conn.execute(
                    select(self._predictions.c.id).where(
                        self._predictions.c.fixture_id == int(new_fixture_id),
                        self._predictions.c.pick == row["pick"],
                        self._predictions.c.result == "PENDING",
                    ).limit(1)
                ).scalar()
                if duplicate and int(duplicate) != int(row["id"]):
                    conn.execute(self._predictions.delete().where(self._predictions.c.id == int(duplicate)))
                result = conn.execute(
                    update(self._predictions)
                    .where(self._predictions.c.id == int(row["id"]), self._predictions.c.result == "PENDING")
                    .values(
                        fixture_id=int(new_fixture_id),
                        recovered_from_fixture_id=int(old_fixture_id),
                        settlement_state="RECOVERED",
                        settlement_reason=reason,
                        settlement_checked_at=datetime.now(timezone.utc).isoformat(),
                        recovery_attempts=func.coalesce(self._predictions.c.recovery_attempts, 0) + 1,
                    )
                )
                updated += int(result.rowcount or 0)
        return updated


    def settlement_investigation_rows(self, limit: int = 100) -> list[dict[str, Any]]:
        # The production predictions table stores the league name in the legacy
        # `league` column. Expose it under the UI-facing alias `league_name` so
        # old PostgreSQL databases and newer templates remain compatible.
        return self._rows("""SELECT id, fixture_id, fixture_date, home_team, away_team,
            league AS league_name, fixture_status, last_api_status, settlement_reason,
            settlement_retry_count, recovery_attempts, settlement_checked_at
            FROM predictions
            WHERE result='PENDING' AND COALESCE(settlement_eligible,1)=1 AND settlement_state='NEEDS_INVESTIGATION'
            ORDER BY SUBSTR(fixture_date,1,10) ASC, id ASC
            LIMIT :n""", {"n": int(limit)})

    def settlement_void_audit(self) -> list[dict[str, Any]]:
        return self._rows("""SELECT
            COALESCE(NULLIF(UPPER(fixture_status), ''), 'UNKNOWN') AS status,
            COUNT(*) AS total
            FROM predictions
            WHERE result='VOID'
            GROUP BY COALESCE(NULLIF(UPPER(fixture_status), ''), 'UNKNOWN')
            ORDER BY total DESC, status ASC""")

    def needs_investigation_count(self) -> int:
        rows = self._rows("""SELECT COUNT(*) AS count FROM predictions
            WHERE result='PENDING' AND COALESCE(settlement_eligible,1)=1 AND settlement_state='NEEDS_INVESTIGATION'""")
        return int(rows[0].get("count") or 0) if rows else 0

    def settlement_totals(self) -> dict[str, int]:
        result_totals = self.settlement_result_totals()
        pending_rows = self._rows("SELECT COUNT(*) AS pending FROM predictions WHERE result='PENDING' AND COALESCE(settlement_eligible,1)=1")
        result_totals["pending"] = int((pending_rows[0] if pending_rows else {}).get("pending") or 0)
        return result_totals

    def settle_prediction_id(self, prediction_id: int, result: str, *, fixture_status: str,
                             home_score: int | None, away_score: int | None) -> bool:
        """Settle one prediction atomically using SQLAlchemy Core.

        Reading and updating happen in the same transaction. The PENDING predicate
        prevents duplicate settlement when manual and scheduled jobs overlap.
        """
        result = result.upper()
        if result not in {"WIN", "LOSS", "VOID"}:
            raise ValueError(f"Unsupported settlement result: {result}")

        with self.engine.begin() as conn:
            row = conn.execute(
                select(self._predictions.c.odds, self._predictions.c.result)
                .where(self._predictions.c.id == int(prediction_id))
                .with_for_update()
            ).mappings().first()
            if not row or row.get("result") != "PENDING":
                return False

            odds = float(row.get("odds") or 1.0)
            profit = (odds - 1.0) if result == "WIN" else (-1.0 if result == "LOSS" else 0.0)
            statement = (
                update(self._predictions)
                .where(
                    self._predictions.c.id == int(prediction_id),
                    self._predictions.c.result == "PENDING",
                )
                .values(
                    result=result,
                    profit=profit,
                    fixture_status=str(fixture_status),
                    home_score=home_score,
                    away_score=away_score,
                    settled_at=datetime.now(timezone.utc).isoformat(),
                    settlement_checked_at=datetime.now(timezone.utc).isoformat(),
                    settlement_state="SETTLED",
                    settlement_reason="Settlement selesai",
                    last_api_status=str(fixture_status),
                    next_retry_at=None,
                )
            )
            update_result = conn.execute(statement)
            return bool(update_result.rowcount)

    def start_automation_run(self, job_name: str, trigger_type: str, started_at: str) -> int:
        with self.engine.begin() as conn:
            result = conn.execute(text("""INSERT INTO automation_runs(job_name,trigger_type,started_at,status)
                VALUES (:j,:tr,:st,'RUNNING') RETURNING id"""),
                {"j": job_name, "tr": trigger_type, "st": started_at})
            return int(result.scalar_one())

    def finish_automation_run(self, run_id: int, status: str, summary: dict[str, Any]) -> None:
        with self.engine.begin() as conn:
            conn.execute(text("""UPDATE automation_runs SET finished_at=:ft,status=:s,summary=:sm WHERE id=:id"""),
                {"ft": datetime.now(timezone.utc).isoformat(), "s": status,
                 "sm": json.dumps(summary, ensure_ascii=False, default=str), "id": run_id})

    def automation_runs(self, limit: int = 50) -> list[dict[str, Any]]:
        rows = self._rows("SELECT * FROM automation_runs ORDER BY id DESC LIMIT :n", {"n": limit})
        for row in rows:
            try:
                row["summary_data"] = json.loads(row.get("summary") or "{}")
            except (TypeError, ValueError):
                row["summary_data"] = {}
        return rows

    def automation_status(self) -> dict[str, Any]:
        totals = self.settlement_totals()
        last = self.automation_runs(1)
        return {**totals, "overdue_pending": self.overdue_pending_count(), "needs_investigation": self.needs_investigation_count(), "last_run": last[0] if last else None}


    # ------------------------------------------------------------------
    # Authentication and membership lifecycle (v7.0 Sprint 1)
    # ------------------------------------------------------------------
    def ensure_admin_user(self, username: str, password: str) -> dict[str, Any]:
        from app.security import hash_password
        now = datetime.now(timezone.utc)
        existing = self.user_by_username(username)
        if existing:
            if existing.get("role") not in {"ADMIN", "SUPER_ADMIN"}:
                with self.engine.begin() as conn:
                    conn.execute(text("UPDATE user_accounts SET role='SUPER_ADMIN',status='ACTIVE',updated_at=:now WHERE id=:id"), {"now": now, "id": existing["id"]})
            return self.user_by_username(username) or existing
        with self.engine.begin() as conn:
            conn.execute(text("""INSERT INTO user_accounts
                (username,full_name,password_hash,role,status,membership_started_at,membership_expires_at,created_at,updated_at)
                VALUES (:username,'Administrator',:password_hash,'SUPER_ADMIN','ACTIVE',:now,NULL,:now,:now)"""),
                {"username": username.strip(), "password_hash": hash_password(password), "now": now})
        return self.user_by_username(username) or {}

    def _normalize_user_dates(self, row: dict[str, Any]) -> dict[str, Any]:
        for key in ("membership_started_at", "membership_expires_at", "last_login_at", "created_at", "updated_at"):
            if row.get(key) not in (None, ""):
                row[key] = self._as_utc(row.get(key))
        return row

    def user_by_username(self, username: str) -> dict[str, Any] | None:
        rows = self._rows("SELECT * FROM user_accounts WHERE lower(username)=lower(:username) LIMIT 1", {"username": username.strip()})
        return self._normalize_user_dates(rows[0]) if rows else None

    def user_by_id(self, user_id: int) -> dict[str, Any] | None:
        rows = self._rows("SELECT * FROM user_accounts WHERE id=:id LIMIT 1", {"id": int(user_id)})
        return self._normalize_user_dates(rows[0]) if rows else None

    @staticmethod
    def _as_utc(value: Any) -> datetime | None:
        if value is None or value == "":
            return None
        if isinstance(value, datetime):
            dt = value
        else:
            dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(timezone.utc)

    def refresh_membership_status(self, user_id: int) -> dict[str, Any] | None:
        user = self.user_by_id(user_id)
        if not user:
            return None
        expiry = self._as_utc(user.get("membership_expires_at"))
        role = str(user.get("role") or "MEMBER").upper()
        status = str(user.get("status") or "ACTIVE").upper()
        if role not in {"ADMIN", "SUPER_ADMIN"} and expiry and datetime.now(timezone.utc) >= expiry and status == "ACTIVE":
            with self.engine.begin() as conn:
                conn.execute(text("UPDATE user_accounts SET status='EXPIRED',updated_at=:now WHERE id=:id"), {"now": datetime.now(timezone.utc), "id": user_id})
            user["status"] = "EXPIRED"
        return user

    def authenticate_user(self, username: str, password: str) -> tuple[dict[str, Any] | None, str | None]:
        from app.security import verify_password
        user = self.user_by_username(username)
        if not user or not verify_password(password, str(user.get("password_hash") or "")):
            return None, "Username atau password salah."
        user = self.refresh_membership_status(int(user["id"])) or user
        status = str(user.get("status") or "DISABLED").upper()
        if status == "EXPIRED":
            return None, "Masa aktif akun Anda telah berakhir. Hubungi administrator untuk perpanjangan."
        if status != "ACTIVE":
            return None, "Akun Anda sedang dinonaktifkan. Hubungi administrator."
        if str(user.get("role") or "MEMBER").upper() == "MEMBER":
            license_row = self.license_for_user(int(user["id"]))
            if not license_row or str(license_row.get("status") or "").upper() != "ACTIVE":
                return None, "License akun tidak aktif atau telah dicabut. Hubungi administrator."
        with self.engine.begin() as conn:
            conn.execute(text("UPDATE user_accounts SET last_login_at=:now,updated_at=:now WHERE id=:id"), {"now": datetime.now(timezone.utc), "id": user["id"]})
        return self.user_by_id(int(user["id"])), None

    def list_users(self, *, query: str | None = None, status: str | None = None,
                   role: str | None = None, expiry: str | None = None) -> list[dict[str, Any]]:
        # Refresh expired memberships before listing so filters and summary always
        # reflect the real login state.
        self.expire_due_memberships()
        clauses: list[str] = []
        params: dict[str, Any] = {}
        if query and query.strip():
            clauses.append("(lower(username) LIKE :query OR lower(COALESCE(full_name,'')) LIKE :query)")
            params["query"] = f"%{query.strip().lower()}%"
        if status and status.upper() in {"ACTIVE", "EXPIRED", "DISABLED"}:
            clauses.append("status=:status")
            params["status"] = status.upper()
        if role and role.upper() in {"SUPER_ADMIN", "ADMIN", "MEMBER"}:
            clauses.append("role=:role")
            params["role"] = role.upper()
        now = datetime.now(timezone.utc)
        if expiry == "EXPIRING_7":
            clauses.append("role='MEMBER' AND status='ACTIVE' AND membership_expires_at IS NOT NULL AND membership_expires_at>:now AND membership_expires_at<=:limit")
            params.update({"now": now, "limit": now + timedelta(days=7)})
        elif expiry == "EXPIRING_30":
            clauses.append("role='MEMBER' AND status='ACTIVE' AND membership_expires_at IS NOT NULL AND membership_expires_at>:now AND membership_expires_at<=:limit")
            params.update({"now": now, "limit": now + timedelta(days=30)})
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        rows = self._rows("SELECT * FROM user_accounts" + where + " ORDER BY CASE role WHEN 'SUPER_ADMIN' THEN 0 WHEN 'ADMIN' THEN 1 ELSE 2 END, id DESC", params)
        for row in rows:
            self._normalize_user_dates(row)
            expiry_dt = self._as_utc(row.get("membership_expires_at"))
            user_role = str(row.get("role") or "MEMBER").upper()
            if user_role in {"ADMIN", "SUPER_ADMIN"} or expiry_dt is None:
                row["days_remaining"] = None
            else:
                seconds = (expiry_dt - now).total_seconds()
                row["days_remaining"] = max(0, int((seconds + 86399) // 86400))
        return rows

    def expire_due_memberships(self) -> int:
        now = datetime.now(timezone.utc)
        with self.engine.begin() as conn:
            result = conn.execute(text("""UPDATE user_accounts
                SET status='EXPIRED', updated_at=:now
                WHERE role='MEMBER' AND status='ACTIVE'
                  AND membership_expires_at IS NOT NULL
                  AND membership_expires_at<=:now"""), {"now": now})
            return int(result.rowcount or 0)

    def membership_summary(self) -> dict[str, int]:
        self.expire_due_memberships()
        now = datetime.now(timezone.utc)
        limit = now + timedelta(days=7)
        rows = self._rows("""SELECT
            COUNT(*) AS total,
            SUM(CASE WHEN status='ACTIVE' THEN 1 ELSE 0 END) AS active,
            SUM(CASE WHEN status='EXPIRED' THEN 1 ELSE 0 END) AS expired,
            SUM(CASE WHEN status='DISABLED' THEN 1 ELSE 0 END) AS disabled,
            SUM(CASE WHEN role='MEMBER' AND status='ACTIVE' AND membership_expires_at>:now AND membership_expires_at<=:limit THEN 1 ELSE 0 END) AS expiring
            FROM user_accounts""", {"now": now, "limit": limit})
        row = rows[0] if rows else {}
        return {key: int(row.get(key) or 0) for key in ("total", "active", "expired", "disabled", "expiring")}

    def update_user_profile(self, user_id: int, *, full_name: str, role: str,
                            membership_expires_at: datetime | None,
                            changed_by: int | None = None, note: str | None = None) -> None:
        user = self.user_by_id(user_id)
        if not user:
            raise ValueError("Akun tidak ditemukan.")
        old_role = str(user.get("role") or "MEMBER").upper()
        new_role = role.upper().strip()
        if new_role not in {"ADMIN", "MEMBER"}:
            raise ValueError("Role tidak valid.")
        if old_role == "SUPER_ADMIN":
            raise ValueError("Akun Super Admin tidak dapat diubah.")
        expiry = self._as_utc(membership_expires_at)
        if new_role == "MEMBER" and expiry is None:
            raise ValueError("Tanggal berakhir wajib diisi untuk member.")
        if new_role == "ADMIN":
            expiry = None
        now = datetime.now(timezone.utc)
        status = str(user.get("status") or "ACTIVE").upper()
        if new_role == "MEMBER" and expiry and expiry <= now:
            status = "EXPIRED"
        elif status == "EXPIRED" and (new_role == "ADMIN" or (expiry and expiry > now)):
            status = "ACTIVE"
        with self.engine.begin() as conn:
            conn.execute(text("""UPDATE user_accounts SET full_name=:full_name, role=:role,
                membership_expires_at=:expiry, status=:status, updated_at=:now WHERE id=:id"""),
                {"full_name": full_name.strip() or str(user.get("username") or ""), "role": new_role,
                 "expiry": expiry, "status": status, "now": now, "id": user_id})
            conn.execute(text("""INSERT INTO membership_history
                (user_id,action,old_expiry,new_expiry,changed_by,note,changed_at)
                VALUES (:user_id,'PROFILE_UPDATED',:old_expiry,:new_expiry,:changed_by,:note,:now)"""),
                {"user_id": user_id, "old_expiry": self._as_utc(user.get("membership_expires_at")),
                 "new_expiry": expiry, "changed_by": changed_by,
                 "note": note or f"Role {old_role} menjadi {new_role}", "now": now})

    def extend_membership_days(self, user_id: int, days: int, *, changed_by: int | None = None,
                               note: str | None = None) -> datetime:
        if days not in {7, 30, 60, 90, 180, 365}:
            raise ValueError("Pilihan durasi tidak valid.")
        user = self.user_by_id(user_id)
        if not user:
            raise ValueError("Akun tidak ditemukan.")
        if str(user.get("role") or "MEMBER").upper() != "MEMBER":
            raise ValueError("Masa aktif hanya berlaku untuk role Member.")
        now = datetime.now(timezone.utc)
        current = self._as_utc(user.get("membership_expires_at"))
        base = current if current and current > now else now
        new_expiry = base + timedelta(days=days)
        self.extend_membership(user_id, new_expiry, changed_by=changed_by, note=note or f"Perpanjangan {days} hari")
        return new_expiry

    def membership_history_detailed(self, user_id: int, limit: int = 100) -> list[dict[str, Any]]:
        rows = self._rows("""SELECT h.*, actor.username AS changed_by_username
            FROM membership_history h
            LEFT JOIN user_accounts actor ON actor.id=h.changed_by
            WHERE h.user_id=:id ORDER BY h.id DESC LIMIT :limit""", {"id": user_id, "limit": limit})
        for row in rows:
            for key in ("old_expiry", "new_expiry", "changed_at"):
                if row.get(key) not in (None, ""):
                    row[key] = self._as_utc(row.get(key))
        return rows

    def create_user(self, *, username: str, full_name: str, password: str, role: str,
                    membership_started_at: datetime | None, membership_expires_at: datetime | None,
                    changed_by: int | None = None) -> int:
        from app.security import hash_password
        clean_username = username.strip()
        if len(clean_username) < 3:
            raise ValueError("Username minimal 3 karakter.")
        if self.user_by_username(clean_username):
            raise ValueError("Username sudah digunakan.")
        role = role.upper().strip()
        if role not in {"ADMIN", "MEMBER"}:
            role = "MEMBER"
        now = datetime.now(timezone.utc)
        start = self._as_utc(membership_started_at) or now
        expiry = self._as_utc(membership_expires_at)
        status = "ACTIVE"
        if role == "MEMBER" and expiry is None:
            raise ValueError("Tanggal berakhir wajib diisi untuk member.")
        if expiry and expiry <= now:
            status = "EXPIRED"
        with self.engine.begin() as conn:
            result = conn.execute(text("""INSERT INTO user_accounts
                (username,full_name,password_hash,role,status,membership_started_at,membership_expires_at,created_at,updated_at)
                VALUES (:username,:full_name,:password_hash,:role,:status,:started,:expires,:now,:now) RETURNING id"""),
                {"username": clean_username, "full_name": full_name.strip() or clean_username,
                 "password_hash": hash_password(password), "role": role, "status": status,
                 "started": start, "expires": expiry, "now": now})
            user_id = int(result.scalar_one())
            if role == "MEMBER":
                from app.security import generate_license_key
                license_key = generate_license_key()
                license_result = conn.execute(text("""INSERT INTO license_records
                    (user_id,license_key,status,activated_at,created_at,updated_at)
                    VALUES (:user_id,:license_key,'ACTIVE',:now,:now,:now) RETURNING id"""),
                    {"user_id": user_id, "license_key": license_key, "now": now})
                license_id = int(license_result.scalar_one())
                conn.execute(text("""INSERT INTO license_history
                    (user_id,license_id,action,new_key,changed_by,note,changed_at)
                    VALUES (:user_id,:license_id,'GENERATED',:new_key,:changed_by,'License dibuat otomatis',:now)"""),
                    {"user_id": user_id, "license_id": license_id, "new_key": license_key, "changed_by": changed_by, "now": now})
            conn.execute(text("""INSERT INTO membership_history
                (user_id,action,old_expiry,new_expiry,changed_by,note,changed_at)
                VALUES (:user_id,'CREATED',NULL,:new_expiry,:changed_by,'Akun dibuat',:now)"""),
                {"user_id": user_id, "new_expiry": expiry, "changed_by": changed_by, "now": now})
        return user_id

    def extend_membership(self, user_id: int, new_expiry: datetime, *, changed_by: int | None = None, note: str | None = None) -> None:
        user = self.user_by_id(user_id)
        if not user:
            raise ValueError("Member tidak ditemukan.")
        expiry = self._as_utc(new_expiry)
        if not expiry or expiry <= datetime.now(timezone.utc):
            raise ValueError("Tanggal perpanjangan harus berada di masa depan.")
        old_expiry = self._as_utc(user.get("membership_expires_at"))
        now = datetime.now(timezone.utc)
        with self.engine.begin() as conn:
            conn.execute(text("UPDATE user_accounts SET membership_expires_at=:expiry,status='ACTIVE',updated_at=:now WHERE id=:id"),
                         {"expiry": expiry, "now": now, "id": user_id})
            conn.execute(text("""INSERT INTO membership_history
                (user_id,action,old_expiry,new_expiry,changed_by,note,changed_at)
                VALUES (:user_id,'EXTENDED',:old_expiry,:new_expiry,:changed_by,:note,:now)"""),
                {"user_id": user_id, "old_expiry": old_expiry, "new_expiry": expiry,
                 "changed_by": changed_by, "note": note or "Masa aktif diperpanjang", "now": now})

    def set_user_status(self, user_id: int, status: str, *, changed_by: int | None = None) -> None:
        user = self.user_by_id(user_id)
        if not user:
            raise ValueError("Akun tidak ditemukan.")
        if str(user.get("role")).upper() == "SUPER_ADMIN":
            raise ValueError("Super Admin tidak dapat dinonaktifkan.")
        status = status.upper().strip()
        if status not in {"ACTIVE", "DISABLED", "EXPIRED"}:
            raise ValueError("Status akun tidak valid.")
        now = datetime.now(timezone.utc)
        with self.engine.begin() as conn:
            conn.execute(text("UPDATE user_accounts SET status=:status,updated_at=:now WHERE id=:id"), {"status": status, "now": now, "id": user_id})
            conn.execute(text("""INSERT INTO membership_history
                (user_id,action,old_expiry,new_expiry,changed_by,note,changed_at)
                VALUES (:user_id,:action,:expiry,:expiry,:changed_by,:note,:now)"""),
                {"user_id": user_id, "action": status, "expiry": self._as_utc(user.get("membership_expires_at")),
                 "changed_by": changed_by, "note": f"Status diubah menjadi {status}", "now": now})

    def reset_user_password(self, user_id: int, new_password: str, *, changed_by: int | None = None) -> None:
        from app.security import hash_password
        if not self.user_by_id(user_id):
            raise ValueError("Akun tidak ditemukan.")
        now = datetime.now(timezone.utc)
        with self.engine.begin() as conn:
            conn.execute(text("UPDATE user_accounts SET password_hash=:password_hash,updated_at=:now WHERE id=:id"),
                         {"password_hash": hash_password(new_password), "now": now, "id": user_id})
            conn.execute(text("""INSERT INTO membership_history
                (user_id,action,changed_by,note,changed_at) VALUES (:user_id,'PASSWORD_RESET',:changed_by,'Password direset oleh admin',:now)"""),
                {"user_id": user_id, "changed_by": changed_by, "now": now})

    def change_own_password(self, user_id: int, current_password: str, new_password: str) -> None:
        from app.security import hash_password, verify_password
        user = self.user_by_id(user_id)
        if not user or not verify_password(current_password, str(user.get("password_hash") or "")):
            raise ValueError("Password saat ini salah.")
        with self.engine.begin() as conn:
            conn.execute(text("UPDATE user_accounts SET password_hash=:password_hash,updated_at=:now WHERE id=:id"),
                         {"password_hash": hash_password(new_password), "now": datetime.now(timezone.utc), "id": user_id})

    def delete_user(self, user_id: int, *, changed_by: int | None = None) -> None:
        user = self.user_by_id(user_id)
        if not user:
            return
        if str(user.get("role")).upper() == "SUPER_ADMIN":
            raise ValueError("Super Admin tidak dapat dihapus.")
        with self.engine.begin() as conn:
            conn.execute(text("DELETE FROM license_history WHERE user_id=:id"), {"id": user_id})
            conn.execute(text("DELETE FROM license_records WHERE user_id=:id"), {"id": user_id})
            conn.execute(text("DELETE FROM membership_history WHERE user_id=:id"), {"id": user_id})
            conn.execute(text("DELETE FROM user_accounts WHERE id=:id"), {"id": user_id})

    def membership_history(self, user_id: int, limit: int = 100) -> list[dict[str, Any]]:
        return self._rows("SELECT * FROM membership_history WHERE user_id=:id ORDER BY id DESC LIMIT :limit", {"id": user_id, "limit": limit})


    # ------------------------------------------------------------------
    # License management (v7.0 Sprint 3)
    # ------------------------------------------------------------------
    def license_for_user(self, user_id: int) -> dict[str, Any] | None:
        rows = self._rows("SELECT * FROM license_records WHERE user_id=:id LIMIT 1", {"id": int(user_id)})
        if not rows:
            return None
        row = rows[0]
        for key in ("activated_at", "revoked_at", "created_at", "updated_at"):
            if row.get(key) not in (None, ""):
                row[key] = self._as_utc(row.get(key))
        return row

    def ensure_user_license(self, user_id: int, *, changed_by: int | None = None) -> dict[str, Any]:
        """Create a license only when the member does not already have one.

        This method is intentionally idempotent for bootstrap/backfill use. UI routes
        that need to distinguish generate vs existing should call create_user_license().
        """
        user = self.user_by_id(user_id)
        if not user:
            raise ValueError("Akun tidak ditemukan.")
        if str(user.get("role") or "MEMBER").upper() != "MEMBER":
            raise ValueError("License hanya berlaku untuk role Member.")
        existing = self.license_for_user(user_id)
        if existing:
            return existing
        from app.security import generate_license_key
        now = datetime.now(timezone.utc)
        key = generate_license_key()
        with self.engine.begin() as conn:
            result = conn.execute(text("""INSERT INTO license_records
                (user_id,license_key,status,activated_at,created_at,updated_at)
                VALUES (:user_id,:key,'ACTIVE',:now,:now,:now) RETURNING id"""),
                {"user_id": user_id, "key": key, "now": now})
            license_id = int(result.scalar_one())
            conn.execute(text("""INSERT INTO license_history
                (user_id,license_id,action,new_key,changed_by,note,changed_at)
                VALUES (:user_id,:license_id,'GENERATED',:key,:changed_by,'License dibuat',:now)"""),
                {"user_id": user_id, "license_id": license_id, "key": key, "changed_by": changed_by, "now": now})
        return self.license_for_user(user_id) or {}


    def create_user_license(self, user_id: int, *, changed_by: int | None = None) -> dict[str, Any]:
        """Create the first license and reject duplicate generate requests."""
        existing = self.license_for_user(user_id)
        if existing:
            raise ValueError("Member sudah memiliki license. Gunakan Ganti License untuk membuat key baru.")
        return self.ensure_user_license(user_id, changed_by=changed_by)

    def rotate_user_license(self, user_id: int, *, changed_by: int | None = None, note: str | None = None) -> dict[str, Any]:
        current = self.license_for_user(user_id)
        if not current:
            raise ValueError("Member belum memiliki license. Gunakan Generate License terlebih dahulu.")
        from app.security import generate_license_key
        new_key = generate_license_key()
        now = datetime.now(timezone.utc)
        with self.engine.begin() as conn:
            conn.execute(text("""UPDATE license_records SET license_key=:new_key,status='ACTIVE',
                activated_at=:now,revoked_at=NULL,updated_at=:now WHERE user_id=:user_id"""),
                {"new_key": new_key, "now": now, "user_id": user_id})
            conn.execute(text("""INSERT INTO license_history
                (user_id,license_id,action,old_key,new_key,changed_by,note,changed_at)
                VALUES (:user_id,:license_id,'ROTATED',:old_key,:new_key,:changed_by,:note,:now)"""),
                {"user_id": user_id, "license_id": current.get("id"), "old_key": current.get("license_key"),
                 "new_key": new_key, "changed_by": changed_by, "note": note or "License diganti", "now": now})
        return self.license_for_user(user_id) or {}

    def set_license_status(self, user_id: int, status: str, *, changed_by: int | None = None, note: str | None = None) -> None:
        current = self.license_for_user(user_id)
        if not current:
            raise ValueError("Member belum memiliki license.")
        status = status.upper().strip()
        if status not in {"ACTIVE", "DISABLED", "REVOKED"}:
            raise ValueError("Status license tidak valid.")
        current_status = str(current.get("status") or "").upper()
        if current_status == status:
            raise ValueError(f"License sudah berstatus {status}.")
        if current_status == "REVOKED" and status == "ACTIVE":
            raise ValueError("License yang telah dicabut tidak dapat diaktifkan kembali. Gunakan Ganti License.")
        now = datetime.now(timezone.utc)
        revoked_at = now if status == "REVOKED" else None
        activated_at = now if status == "ACTIVE" else current.get("activated_at")
        with self.engine.begin() as conn:
            conn.execute(text("""UPDATE license_records SET status=:status,activated_at=:activated_at,
                revoked_at=:revoked_at,updated_at=:now WHERE user_id=:user_id"""),
                {"status": status, "activated_at": activated_at, "revoked_at": revoked_at, "now": now, "user_id": user_id})
            conn.execute(text("""INSERT INTO license_history
                (user_id,license_id,action,old_key,new_key,changed_by,note,changed_at)
                VALUES (:user_id,:license_id,:action,:key,:key,:changed_by,:note,:now)"""),
                {"user_id": user_id, "license_id": current.get("id"), "action": status, "key": current.get("license_key"),
                 "changed_by": changed_by, "note": note or f"Status license menjadi {status}", "now": now})

    def license_history_detailed(self, user_id: int, limit: int = 100) -> list[dict[str, Any]]:
        rows = self._rows("""SELECT h.*, actor.username AS changed_by_username
            FROM license_history h LEFT JOIN user_accounts actor ON actor.id=h.changed_by
            WHERE h.user_id=:id ORDER BY h.id DESC LIMIT :limit""", {"id": user_id, "limit": limit})
        def mask_key(value: Any) -> str | None:
            text_value = str(value or "").strip()
            if not text_value:
                return None
            if len(text_value) <= 8:
                return "****"
            return f"{text_value[:5]}-****-****-{text_value[-4:]}"

        for row in rows:
            if row.get("changed_at") not in (None, ""):
                row["changed_at"] = self._as_utc(row.get("changed_at"))
            row["old_key_masked"] = mask_key(row.get("old_key"))
            row["new_key_masked"] = mask_key(row.get("new_key"))
        return rows
